"""PyMOL CLI - PyMOL script (.pml) generation from JSON project state.

Generates complete PyMOL scripts that reproduce the entire session state
including structure loading, representations, colors, labels, view, and rendering.
"""

from typing import Dict, Any, Optional, List


def generate_full_script(
    project: Dict[str, Any],
    output_path: str,
    ray: Optional[bool] = None,
) -> str:
    """Generate a complete PyMOL .pml script from the project state.

    Args:
        project: Project dict.
        output_path: Path for the output image.
        ray: Override ray tracing setting.

    Returns:
        Complete .pml script as string.
    """
    lines = []
    lines.append("# PyMOL script generated by cli-anything-pymol")
    lines.append("# ================================================")
    lines.append("")

    # Reinitialize
    lines.append("reinitialize")
    lines.append("")

    # Global settings
    _gen_settings(lines, project)

    # Load structures
    _gen_structures(lines, project)

    # Selections
    _gen_selections(lines, project)

    # Representations
    _gen_representations(lines, project)

    # Colors
    _gen_colors(lines, project)

    # Labels
    _gen_labels(lines, project)

    # View
    _gen_view(lines, project)

    # Render
    render = project.get("render", {})
    use_ray = ray if ray is not None else render.get("ray", True)
    _gen_render(lines, project, output_path, use_ray)

    lines.append("")
    lines.append("# End of script")

    return "\n".join(lines)


def _gen_settings(lines: List[str], project: Dict[str, Any]):
    """Generate global settings commands."""
    settings = project.get("settings", {})
    lines.append("# --- Settings ---")

    bg = settings.get("bg_color", [0, 0, 0])
    lines.append(f"bg_color [{bg[0]}, {bg[1]}, {bg[2]}]")

    if settings.get("depth_cue", True):
        lines.append("set depth_cue, 1")
    else:
        lines.append("set depth_cue, 0")

    if settings.get("fog", False):
        lines.append("set fog, 1")
    else:
        lines.append("set fog, 0")

    lines.append(f"set antialias, {settings.get('antialias', 2)}")
    lines.append(f"set ray_trace_mode, {settings.get('ray_trace_mode', 1)}")

    if settings.get("valence", True):
        lines.append("set valence, 1")
    else:
        lines.append("set valence, 0")

    if settings.get("orthoscopic", True):
        lines.append("set orthoscopic, on")
    else:
        lines.append("set orthoscopic, off")

    fov = settings.get("field_of_view", 20.0)
    lines.append(f"set field_of_view, {fov}")

    lines.append("")


def _gen_structures(lines: List[str], project: Dict[str, Any]):
    """Generate structure loading commands."""
    structures = project.get("structures", [])
    if not structures:
        return

    lines.append("# --- Load structures ---")
    for s in structures:
        pdb_id = s.get("pdb_id")
        path = s.get("path")
        obj_name = s.get("object_name", "structure")

        if pdb_id:
            lines.append(f"fetch {pdb_id}, name={obj_name}, async=0")
        elif path:
            lines.append(f"load {path}, {obj_name}")

        if not s.get("visible", True):
            lines.append(f"disable {obj_name}")

    lines.append("")


def _gen_selections(lines: List[str], project: Dict[str, Any]):
    """Generate selection commands."""
    selections = project.get("selections", [])
    if not selections:
        return

    lines.append("# --- Selections ---")
    for sel in selections:
        if sel.get("enabled", True):
            name = sel["name"]
            expr = sel["expression"]
            lines.append(f"select {name}, {expr}")
        else:
            lines.append(f"# (disabled) select {sel['name']}, {sel['expression']}")

    lines.append("deselect")
    lines.append("")


def _gen_representations(lines: List[str], project: Dict[str, Any]):
    """Generate representation commands."""
    representations = project.get("representations", [])
    if not representations:
        return

    lines.append("# --- Representations ---")

    # First hide everything
    lines.append("hide everything, all")
    lines.append("")

    for rep in representations:
        target = rep["target"]
        rep_type = rep["rep_type"]
        enabled = rep.get("enabled", True)
        settings = rep.get("settings", {})

        if enabled:
            lines.append(f"show {rep_type}, {target}")

        # Apply settings
        for key, value in settings.items():
            lines.append(f"set {key}, {value}, {target}")

    lines.append("")


def _gen_colors(lines: List[str], project: Dict[str, Any]):
    """Generate color commands."""
    colors = project.get("colors", [])
    if not colors:
        return

    lines.append("# --- Colors ---")
    for col in colors:
        target = col["target"]
        color_type = col.get("color_type", "named")

        if color_type == "named":
            color_name = col.get("color_name", "white")
            lines.append(f"color {color_name}, {target}")
        elif color_type == "rgb":
            rgb = col.get("color_rgb", [1, 1, 1])
            # Define a custom color
            color_id = f"custom_{col.get('id', 0)}"
            lines.append(f"set_color {color_id}, [{rgb[0]}, {rgb[1]}, {rgb[2]}]")
            lines.append(f"color {color_id}, {target}")
        elif color_type == "scheme":
            scheme = col.get("scheme", "by_element")
            from cli_anything.pymol.core.coloring import COLOR_SCHEMES
            if scheme in COLOR_SCHEMES:
                pymol_cmd = COLOR_SCHEMES[scheme]["pymol_command"]
                # Some commands take target, some don't
                if "spectrum" in pymol_cmd:
                    parts = pymol_cmd.split(", ")
                    if len(parts) > 1:
                        lines.append(f"{parts[0]}, {parts[1]}, {target}")
                    else:
                        lines.append(f"{pymol_cmd}, selection={target}")
                elif "util." in pymol_cmd:
                    lines.append(f"python")
                    lines.append(f"from pymol import cmd")
                    lines.append(f"cmd.do('{pymol_cmd}(\"{target}\")')")
                    lines.append(f"python end")
                else:
                    lines.append(f"{pymol_cmd}, {target}")

    lines.append("")


def _gen_labels(lines: List[str], project: Dict[str, Any]):
    """Generate label commands."""
    labels = project.get("labels", [])
    if not labels:
        return

    lines.append("# --- Labels ---")
    for lbl in labels:
        target = lbl["target"]
        expression = lbl["expression"]
        color = lbl.get("color", [1, 1, 1])
        size = lbl.get("size", 14)

        lines.append(f"set label_size, {size}")
        # Set label color
        lines.append(f"set label_color, [{color[0]}, {color[1]}, {color[2]}], {target}")
        lines.append(f'label {target}, {expression}')

    lines.append("")


def _gen_view(lines: List[str], project: Dict[str, Any]):
    """Generate view/camera commands."""
    view = project.get("view", {})
    if not view:
        return

    lines.append("# --- View ---")

    # If we have structures, orient to them
    if project.get("structures"):
        lines.append("orient")

    zoom = view.get("zoom", 1.0)
    if zoom != 1.0:
        lines.append(f"zoom all, {zoom}")

    clip_near = view.get("clip_near")
    clip_far = view.get("clip_far")
    if clip_near is not None and clip_far is not None:
        lines.append(f"clip near, {clip_near}")
        lines.append(f"clip far, {clip_far}")

    lines.append("")


def _gen_render(
    lines: List[str],
    project: Dict[str, Any],
    output_path: str,
    use_ray: bool,
):
    """Generate render/export commands."""
    render = project.get("render", {})
    width = render.get("width", 1920)
    height = render.get("height", 1080)
    output_format = render.get("output_format", "png")
    dpi = render.get("dpi", 300)
    transparent = render.get("transparent_background", False)

    lines.append("# --- Render ---")

    if transparent:
        lines.append("set ray_opaque_background, 0")
    else:
        lines.append("set ray_opaque_background, 1")

    ray_shadows = render.get("ray_shadows", True)
    if not ray_shadows:
        lines.append("set ray_shadows, 0")

    if use_ray:
        lines.append(f"ray {width}, {height}")
    else:
        lines.append(f"viewport {width}, {height}")
        lines.append("draw")

    lines.append(f'png {output_path}, dpi={dpi}')
    lines.append("")
    lines.append("quit")
