"""Fiji CLI - Macro management module.

Stores, lists, and builds ImageJ macros for batch execution.
"""

from datetime import datetime
from typing import Dict, Any, List, Optional


def add_macro(
    project: Dict[str, Any],
    code: str,
    name: Optional[str] = None,
    description: str = "",
) -> Dict[str, Any]:
    """Add a custom macro to the project.

    Args:
        project: The project dict.
        code: ImageJ macro code.
        name: Macro name (auto-generated if not provided).
        description: Optional description.
    """
    if "macros" not in project:
        project["macros"] = []

    idx = len(project["macros"])
    if name is None:
        name = f"macro_{idx}"

    entry = {
        "id": idx,
        "name": name,
        "description": description,
        "code": code,
        "created": datetime.now().isoformat(),
    }
    project["macros"].append(entry)
    return entry


def remove_macro(project: Dict[str, Any], index: int) -> Dict[str, Any]:
    """Remove a macro by index."""
    macros = project.get("macros", [])
    if index < 0 or index >= len(macros):
        raise IndexError(f"Macro index {index} out of range (0-{len(macros) - 1})")
    removed = macros.pop(index)
    for i, m in enumerate(macros):
        m["id"] = i
    return removed


def list_macros(project: Dict[str, Any]) -> List[Dict[str, Any]]:
    """List all macros."""
    return [
        {
            "id": m["id"],
            "name": m["name"],
            "description": m.get("description", ""),
            "code_length": len(m["code"]),
        }
        for m in project.get("macros", [])
    ]


def get_macro(project: Dict[str, Any], index: int) -> Dict[str, Any]:
    """Get a specific macro."""
    macros = project.get("macros", [])
    if index < 0 or index >= len(macros):
        raise IndexError(f"Macro index {index} out of range (0-{len(macros) - 1})")
    return macros[index]


def build_batch_macro(
    project: Dict[str, Any],
    input_dir: str,
    output_dir: str,
    file_pattern: str = ".*\\.tif",
    macro_index: Optional[int] = None,
) -> str:
    """Build a batch processing macro.

    Creates an ImageJ macro that iterates over files in input_dir,
    applies processing steps (or a stored macro), and saves results
    to output_dir.

    Args:
        project: The project dict.
        input_dir: Directory with input images.
        output_dir: Directory for output images.
        file_pattern: Regex pattern to match files.
        macro_index: Index of stored macro to use (or None for processing log).
    """
    if macro_index is not None:
        macros = project.get("macros", [])
        if macro_index < 0 or macro_index >= len(macros):
            raise IndexError(f"Macro index {macro_index} out of range")
        user_code = macros[macro_index]["code"]
    else:
        # Build from processing log
        from cli_anything.fiji.core.processing import build_macro
        user_code = build_macro(project)

    macro = f'''
// Fiji batch processing macro
// Generated by fiji-cli

input = "{input_dir}";
output = "{output_dir}";

setBatchMode(true);
list = getFileList(input);
for (i = 0; i < list.length; i++) {{
    if (matches(list[i], "{file_pattern}")) {{
        open(input + File.separator + list[i]);
        // --- User processing steps ---
{_indent(user_code, 8)}
        // --- End user steps ---
        saveAs("Tiff", output + File.separator + list[i]);
        close();
    }}
}}
setBatchMode(false);
print("Batch complete: " + list.length + " files processed");
'''
    return macro.strip()


def _indent(text: str, spaces: int) -> str:
    """Indent each line of text."""
    prefix = " " * spaces
    return "\n".join(prefix + line for line in text.split("\n"))
